backend:
    image:
        repository: danieloncode/oncodepayment-backend
        tag: a1907e14cd0286b71c071c7de54e668ebc89c5d9
        pullPolicy: IfNotPresent
    replicas: 1
    port: 8098
    env:
        dbUsername: oncode
        dbDriver: org.postgresql.Driver
        jpaDialect: org.hibernate.dialect.PostgreSQLDialect
        jpaDdlAuto: update

frontend:
    image:
        repository: danieloncode/oncodepayment-frontend
        tag: a1907e14cd0286b71c071c7de54e668ebc89c5d9
        pullPolicy: IfNotPresent
    replicas: 1
    port: 80

postgresql:
    image: postgres:16-alpine
    port: 5432
    database: paymentdb
    existingSecret: oncodepayment-secret
    awsSecretName: oncodepayment-dev/postgres
    storage: 1Gi
    storageClass: standard

ingress:
    enabled: true
    className: nginx
    host: oncodepayment.local
