apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend"
  labels:
    name: "{{ .Release.Name }}-frontend"
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      name: "{{ .Release.Name }}-frontend"
  template:
    metadata:
      labels:
        name: "{{ .Release.Name }}-frontend"
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: API_UPSTREAM
              value: "{{ .Release.Name }}-backend-service:{{ .Values.backend.port }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
