apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-postgres-service"
  labels:
    name: "{{ .Release.Name }}-postgres-service"
spec:
  selector:
    name: "{{ .Release.Name }}-postgres"
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  type: ClusterIP
