apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    name: "{{ .Release.Name }}-secret"
type: Opaque
data:
  DB_USERNAME: {{ .Values.postgresql.username | b64enc }}
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc }}
