# Workflow Actions

name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run "OncodePayment_Recorder.postman_collection.json" -e OncodePayment.postman_environment.json
